# Generated by Django 5.1 on 2024-08-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_histoy', 'Can view history')]},
        ),
    ]
